create table if not exists public.items (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default '客厅',
  assignee text not null default '一起',
  price integer not null default 0,
  kind text not null default 'task' check (kind in ('task', 'wish')),
  completed integer not null default 0 check (completed in (0, 1)),
  sort_order integer not null default 0
);

create index if not exists idx_items_kind_sort on public.items(kind, sort_order);
alter table public.items enable row level security;
create policy "server api can manage home items"
on public.items for all to anon
using (true)
with check (true);
